name: itegracion continua con node.js
on:
  push:
    branches:    
      - development
jobs: 
  ci_to_master:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with: 
        node-version: 14.7.0
        cache: 'npm'
    - run: yarn install
    - run: npm install
    - run: chmod 777 ./base.sh
    - run: sed -i "s/PROJECT/kpmgboapi/g" ./base.sh
    - run: sed -i "s/%ENV/development/g" ./base.sh
    - run: chmod 777 ./base.sh
    - run: sed -i "s/PROJECT/kpmgboapi/g" ./package.json
    - run: sed -i "s/.env.production/.env.development/g" ./package.json
    - run: sed -i "s/NODE_ENV=production tsc/NODE_ENV=development tsc/g" ./package.json
    - run: sed -i "s/NODE_ENV=production babel/NODE_ENV=development babel/g" ./package.json
    - run: yarn super:build
    - uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: 'root'
        server: '52.12.254.63'
        ssh_private_key: './cert/node_kpmg.pem'
        local_path: './dist/*'
        remote_path: '/home/kpmgboapi/'
        args: '-o ConnectTimeout=5'
    - run: ls -alhr
    - run: chmod 400 ./cert/node_kpmg.pem
    - run: ssh -i ./cert/node_kpmg.pem node_kpmg@52.12.254.63 /home/kpmgboapi/base.sh